language: python
sudo: false

python:
  - 3.6
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update conda --yes
  - export CONDARC=ci/condarc


install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda install --file requirements/run --file requirements/test
  - python setup.py install


script:
  - coverage run run_tests.py
  - coverage report -m
  - codecov
